# Apa ini?
tujuan notebook ini buat ngeliat informasi apa aja yang bisa diambil dari setiap dataset SFT yang udah jadi.

misal untuk dataset Ujaran Kebencian, kebanyakan bahas suku atau agama atau apa
untuk fitnah siapa yang paling sering diserang? pemerintah? polisi? 
dll

In [1]:
import pandas as pd
from pathlib import Path

# EDA Ujaran Kebencian

In [16]:
folderData = Path("Dataset_Fitnah")
folderSFT = Path("DatasetAkhir")
hasil = folderSFT / "fitnah.jsonl"
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

df_faktaSFT = pd.read_json(hasil, lines=True)

In [4]:
df

,url,title,published_at,text,sumber_berita,label,is_layak,claim_fitnah,cot_bantah_fitnah,reasoning_fitnah,cot_bantuh_fitnah
0,https://news.indozone.id/hukum/2486475324/bnn-...,"BNN Gerebek Narkoba di Berlan Matraman, Puluha...",2025-11-25 22:05:10,"BNN menggedebek kampung narkoba di Berlan, Mat...",indozone,Kriminalitas,1.0,BNN sengaja pilih kampung miskin buat dijadika...,"[BNN melakukan penggerebekan di Berlan, Matram...",Fakta dipelintir dengan menuduh BNN memilih ka...,NaN
1,https://www.cnbcindonesia.com/mymoney/20260226...,"Video: 2026, Asuransi Perkuat Modal-Tingkatkan...",N/A,CNBC Indonesia menyelenggarakan Insurance Foru...,cnbcindonesia,Ekonomi & Bisnis,0.0,NaN,[NaN],NaN,NaN
2,https://kaltim.indozone.id/news/2486148036/dpr...,DPRD Berau Soroti Rendahnya Serapan Anggaran S...,2025-07-29 19:47:06,KALIMANTAN TIMUR - Serapan anggaran Pemerintah...,indozone,Politik,1.0,DPRD Berau sengaja lambatkan serapan anggaran ...,[DPRD Berau menyoroti rendahnya serapan anggar...,Claim ini menggunakan framing negatif dan insi...,NaN
3,https://news.indozone.id/politik/913172017/pun...,"Punya Peran Besar, Sandiaga Kukuhkan Relawan D...",2023-10-30 11:41:59,Sandiaga Uno dalam acara silaturahmi dengan pa...,indozone,Politik,1.0,Sandiaga Uno hanya memanfaatkan relawan untuk ...,[Sandiaga Uno mengingatkan relawan untuk mendu...,Claim ini menggunakan framing negatif dan insi...,NaN
4,https://news.indozone.id/tau-gak-sih/248661408...,BPBD DKI Jakarta Kembali Lakukan OMC untuk Ant...,2026-01-31 18:09:34,Ilustrasi cuaca ekstrem. (ANTARA FOTO/Dedhez A...,indozone,Bencana & Keamanan,1.0,"BPBD DKI Jakarta main-main sama cuaca, bikin h...",[Operasi Modifikasi Cuaca (OMC) adalah tindaka...,Claim ini memanfaatkan framing negatif dan ins...,NaN
...,...,...,...,...,...,...,...,...,...,...,...
14640,https://economy.okezone.com/read/2026/03/25/32...,KAI Logistik Catat Volume Angkut 5.740 Ton Sel...,2026-03-25T17:34:47+07:00,- PT Kereta Api Logistik () mencatat kinerja p...,okezone,Ekonomi & Bisnis,0.0,NaN,[NaN],NaN,NaN
14641,https://news.okezone.com/read/2026/03/22/18/32...,Putri Kim Jong Un Ikut Kendarai Tank dalam Lat...,2026-03-22T02:05:10+07:00,Pemimpin Korea Utara Kim Jong Un membawa putri...,okezone,Politik,1.0,Putri Kim Jong Un dikendalikan untuk jadi alat...,"[Putri Kim Jong Un, Kim Ju-ae, terlibat dalam ...",Fakta dipelintir dengan mengeksploitasi gambar...,NaN
14642,https://news.okezone.com/read/2025/08/22/337/3...,Ini Hal yang Memberatkan Eks Ketua PN Surabaya...,2025-08-22T11:58:29+07:00,– Mantan Ketua Pengadilan Negeri (PN) Surabaya...,okezone,Politik,NaN,NaN,NaN,NaN,NaN
14643,https://news.okezone.com/read/2025/07/16/519/3...,Viral! Makanan Siswa Program Bergizi di Tuban ...,2025-07-16T10:38:16+07:00,- Warganet dihebohkan dengan beredarnya video ...,okezone,Kriminalitas,1.0,Pemerintah sengaja beri makan belatung ke sisw...,[Fakta menyebutkan bahwa kejadian ini terjadi ...,Narrasi ini menggunakan teknik framing negatif...,NaN
14644,https://news.okezone.com/read/2025/04/21/512/3...,"Incar Wanita Jadi Korbannya, Polres Semarang T...",2025-04-21T16:50:32+07:00,- Polres Semarang menangkap seorang residivis ...,okezone,Kriminalitas,0.0,NaN,[NaN],NaN,NaN

In [7]:
df_faktaSFT

,instruction,input,output
0,Bandingkan narasi berikut dengan rujukan resmi...,input: BNN sengaja pilih kampung miskin buat d...,Label: **Fitnah.** penjelasan: Fakta dipelinti...
1,Tentukan kategori teks ini berdasarkan bukti-b...,input: DPRD Berau sengaja lambatkan serapan an...,Label: **Fitnah.** penjelasan: Claim ini mengg...
2,Ukur tingkat akurasi teks ini terhadap artikel...,input: Sandiaga Uno hanya memanfaatkan relawan...,Label: **Fitnah.** penjelasan: Claim ini mengg...
3,Bandingkan narasi berikut dengan rujukan resmi...,"input: BPBD DKI Jakarta main-main sama cuaca, ...",Label: **Fitnah.** penjelasan: Claim ini meman...
4,Bantu klasifikasikan teks ini ke label Disinfo...,input: Pemprov Sumut hanya main-main dengan UH...,Label: **Fitnah.** penjelasan: Fakta menunjukk...
...,...,...,...
7207,Lakukan verifikasi data. Berdasarkan artikel r...,"input: MNC Group hanya pura-pura peduli, progr...",Label: **Fitnah.** penjelasan: Narasi ini meng...
7208,Analisis korelasi antara teks dan artikel ruju...,input: Erick Thohir main-main dengan isu pelec...,Label: **Fitnah.** penjelasan: Claim tersebut ...
7209,Lakukan uji validasi akhir. Bandingkan klaim d...,"input: Polisi Lubuklinggau settingan, biarin a...",Label: **Fitnah.** penjelasan: Claim ini mengg...
7210,Lakukan verifikasi data. Berdasarkan artikel r...,input: Putri Kim Jong Un dikendalikan untuk ja...,Label: **Fitnah.** penjelasan: Fakta dipelinti...
7211,Bantu sistem menentukan validitas teks ini (Fa...,input: Pemerintah sengaja beri makan belatung ...,Label: **Fitnah.** penjelasan: Narrasi ini men...

In [17]:
df_faktaSFT["claim"] = df_faktaSFT["input"].str.extract(r"input: (.*?);\n\n")[0]

In [9]:
df_faktaSFT

,instruction,input,output,claim
0,Bandingkan narasi berikut dengan rujukan resmi...,input: BNN sengaja pilih kampung miskin buat d...,Label: **Fitnah.** penjelasan: Fakta dipelinti...,BNN sengaja pilih kampung miskin buat dijadika...
1,Tentukan kategori teks ini berdasarkan bukti-b...,input: DPRD Berau sengaja lambatkan serapan an...,Label: **Fitnah.** penjelasan: Claim ini mengg...,DPRD Berau sengaja lambatkan serapan anggaran ...
2,Ukur tingkat akurasi teks ini terhadap artikel...,input: Sandiaga Uno hanya memanfaatkan relawan...,Label: **Fitnah.** penjelasan: Claim ini mengg...,Sandiaga Uno hanya memanfaatkan relawan untuk ...
3,Bandingkan narasi berikut dengan rujukan resmi...,"input: BPBD DKI Jakarta main-main sama cuaca, ...",Label: **Fitnah.** penjelasan: Claim ini meman...,"BPBD DKI Jakarta main-main sama cuaca, bikin h..."
4,Bantu klasifikasikan teks ini ke label Disinfo...,input: Pemprov Sumut hanya main-main dengan UH...,Label: **Fitnah.** penjelasan: Fakta menunjukk...,"Pemprov Sumut hanya main-main dengan UHC, masy..."
...,...,...,...,...
7207,Lakukan verifikasi data. Berdasarkan artikel r...,"input: MNC Group hanya pura-pura peduli, progr...",Label: **Fitnah.** penjelasan: Narasi ini meng...,"MNC Group hanya pura-pura peduli, program Pedu..."
7208,Analisis korelasi antara teks dan artikel ruju...,input: Erick Thohir main-main dengan isu pelec...,Label: **Fitnah.** penjelasan: Claim tersebut ...,Erick Thohir main-main dengan isu pelecehan se...
7209,Lakukan uji validasi akhir. Bandingkan klaim d...,"input: Polisi Lubuklinggau settingan, biarin a...",Label: **Fitnah.** penjelasan: Claim ini mengg...,"Polisi Lubuklinggau settingan, biarin aja grup..."
7210,Lakukan verifikasi data. Berdasarkan artikel r...,input: Putri Kim Jong Un dikendalikan untuk ja...,Label: **Fitnah.** penjelasan: Fakta dipelinti...,Putri Kim Jong Un dikendalikan untuk jadi alat...
7211,Bantu sistem menentukan validitas teks ini (Fa...,input: Pemerintah sengaja beri makan belatung ...,Label: **Fitnah.** penjelasan: Narrasi ini men...,Pemerintah sengaja beri makan belatung ke sisw...

In [18]:
df_faktaSFT = (
    df_faktaSFT.merge(
        df[["claim_fitnah", "label", "published_at"]],
        left_on=["claim"],
        right_on=["claim_fitnah"],
        how="left"
    )
)

In [19]:
df_faktaSFT

,instruction,input,output,claim,claim_fitnah,label,published_at
0,Bandingkan narasi berikut dengan rujukan resmi...,input: BNN sengaja pilih kampung miskin buat d...,Label: **Fitnah.** penjelasan: Fakta dipelinti...,BNN sengaja pilih kampung miskin buat dijadika...,BNN sengaja pilih kampung miskin buat dijadika...,Kriminalitas,2025-11-25 22:05:10
1,Tentukan kategori teks ini berdasarkan bukti-b...,input: DPRD Berau sengaja lambatkan serapan an...,Label: **Fitnah.** penjelasan: Claim ini mengg...,DPRD Berau sengaja lambatkan serapan anggaran ...,DPRD Berau sengaja lambatkan serapan anggaran ...,Politik,2025-07-29 19:47:06
2,Ukur tingkat akurasi teks ini terhadap artikel...,input: Sandiaga Uno hanya memanfaatkan relawan...,Label: **Fitnah.** penjelasan: Claim ini mengg...,Sandiaga Uno hanya memanfaatkan relawan untuk ...,Sandiaga Uno hanya memanfaatkan relawan untuk ...,Politik,2023-10-30 11:41:59
3,Bandingkan narasi berikut dengan rujukan resmi...,"input: BPBD DKI Jakarta main-main sama cuaca, ...",Label: **Fitnah.** penjelasan: Claim ini meman...,"BPBD DKI Jakarta main-main sama cuaca, bikin h...","BPBD DKI Jakarta main-main sama cuaca, bikin h...",Bencana & Keamanan,2026-01-31 18:09:34
4,Bantu klasifikasikan teks ini ke label Disinfo...,input: Pemprov Sumut hanya main-main dengan UH...,Label: **Fitnah.** penjelasan: Fakta menunjukk...,"Pemprov Sumut hanya main-main dengan UHC, masy...","Pemprov Sumut hanya main-main dengan UHC, masy...",Kesehatan,2025-09-18 10:30:00
...,...,...,...,...,...,...,...
7207,Lakukan verifikasi data. Berdasarkan artikel r...,"input: MNC Group hanya pura-pura peduli, progr...",Label: **Fitnah.** penjelasan: Narasi ini meng...,"MNC Group hanya pura-pura peduli, program Pedu...","MNC Group hanya pura-pura peduli, program Pedu...",Politik,2026-02-04T11:13:13+07:00
7208,Analisis korelasi antara teks dan artikel ruju...,input: Erick Thohir main-main dengan isu pelec...,Label: **Fitnah.** penjelasan: Claim tersebut ...,Erick Thohir main-main dengan isu pelecehan se...,Erick Thohir main-main dengan isu pelecehan se...,Politik,2026-02-26T20:55:13+07:00
7209,Lakukan uji validasi akhir. Bandingkan klaim d...,"input: Polisi Lubuklinggau settingan, biarin a...",Label: **Fitnah.** penjelasan: Claim ini mengg...,"Polisi Lubuklinggau settingan, biarin aja grup...","Polisi Lubuklinggau settingan, biarin aja grup...",Kriminalitas,2025-07-19T09:10:33+07:00
7210,Lakukan verifikasi data. Berdasarkan artikel r...,input: Putri Kim Jong Un dikendalikan untuk ja...,Label: **Fitnah.** penjelasan: Fakta dipelinti...,Putri Kim Jong Un dikendalikan untuk jadi alat...,Putri Kim Jong Un dikendalikan untuk jadi alat...,Politik,2026-03-22T02:05:10+07:00
7211,Bantu sistem menentukan validitas teks ini (Fa...,input: Pemerintah sengaja beri makan belatung ...,Label: **Fitnah.** penjelasan: Narrasi ini men...,Pemerintah sengaja beri makan belatung ke sisw...,Pemerintah sengaja beri makan belatung ke sisw...,Kriminalitas,2025-07-16T10:38:16+07:00

In [ ]:
df_faktaSFT["label"].unique()